#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2017 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2017 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################
---
#file: roles/upgrade/tasks/mpf-to-current.yml

  - name: Load MPF to Current Release variables
    include_vars: mpf-to-current/vars.yml

  - include: mpf-to-current/mysql.yml
    delegate_to: "{{ master_host }}"
    run_once: true

  - include: mpf-to-current/customPipelines.yml
    delegate_to: "{{ master_host }}"
    run_once: true

  - include: mpf-to-current/customProperties.yml
    delegate_to: "{{ master_host }}"
    run_once: true

  # Previous releases of openmpf used path $MPF_HOME/share/components/components.json,
  # releases 0.9+ use $MPF_HOME/data/components.json
  - name: Check for previous version of components JSON file
    stat:
      path: "{{ mpf_home }}/data/components.json"
    register: old_components_st
    run_once: true

  - name: Backup previous version of components.json file
    copy:
      src: "{{ mpf_home }}/data/components.json"
      dest: "{{ mpf_home }}/data/components.json.bak"
    delegate_to: "{{ master_host }}"
    run_once: true
    when: old_components_st.stat.exists

  - name: Remove previous version of components.json file
    file:
      path: "{{ mpf_home }}/data/components.json"
      state: absent
    delegate_to: "{{ master_host }}"
    run_once: true
    when: old_components_st.stat.exists

  - name: Find old .jar files
    find:
      paths: "{{ mpf_home }}/jars"
      patterns: "mpf*-0.8.0.jar"
    register: oldjar_find

  - name: Remove old .jar files
    file:
      path="{{ item.path }}"
      state=absent
    with_items: "{{ oldjar_find.files }}"
    when: "{{ oldjar_find.matched|int|default(0) }} > 0"