#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2016 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2016 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################
---
#file: roles/upgrade/tasks/8to9/customProperties.yml

  - name: Check for mpf-custom.properties file
    stat:
      path="{{ tomcat_home }}/webapps/workflow-manager/WEB-INF/classes/properties/mpf-custom.properties"
    register: custom_properties_st

  - name: Check for mpf-custom.properties symlink
    stat:
      path="{{ mpf_home }}/config/mpf-custom.properties"
    register: custom_properties_lnk_st

  - name: "Remove {{ mpf_home }}/config/mpf-custom.properties symlink"
    file:
      path="{{ mpf_home }}/config/mpf-custom.properties"
      state=absent
    when: custom_properties_lnk_st.stat.islnk is defined and custom_properties_lnk_st.stat.islnk

  - name: "Copy mpf-custom.properties to {{ mpf_home }}/config/mpf-custom.properties"
    copy:
      src="{{ tomcat_home }}/webapps/workflow-manager/WEB-INF/classes/properties/mpf-custom.properties"
      dest="{{ mpf_home }}/config/mpf-custom.properties"
    when: custom_properties_st.stat.exists
