#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2017 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2017 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################
---
# file: mpf-child.yml
- hosts: mpf-child
  roles:
    - child
  tags: configure, compdeploy, compreg
  remote_user: mpf
  become: yes
  vars:
    - deployment_config: "{{ lookup('file', '{{ mpf_home }}/share/deployment_config.json') | from_json }}"
    - plugins_dir: "{{ mpf_home }}/plugins"
    - mpf_component_dir: "{{ mpf_home }}/share/components"
  pre_tasks:
    - name: Validate Number of MPF Master hosts
      fail: msg="The number of Master hosts must be exactly 1!"
      when: num_master_hosts | int != 1

    - name: Add localhost to repo inventory
      add_host: name={{ inventory_hostname }} groups=mpf-repo

  post_tasks:
    - name: Get MPF component descriptors
      set_fact:
        mpf_descriptor_paths: "{% set temp_list = [] %}{% for component in deployment_config.mpf_components %}{% if component.register %}{{ temp_list.append(component.componentDescriptorPath) }}{% endif %}{% endfor %}{{ temp_list }}"
      delegate_to: "{{ master_host }}"

    - name: Check for existence of keystore file
      stat:
        path="{{ deployment_config.https.keystore_file }}"
      when: deployment_config.https.install
      register: keystore_filest
      delegate_to: "{{ master_host }}"
      run_once: true

    - name: Register MPF components
      include: "{{ mpf_home }}/manage/ansible/roles/child/tasks/compregistration.yml"
      with_items:
        - "{{ deployment_config.mpf_components }}"

    - name: Run post-install upgrade steps
      debug: msg="Running handler..."
      notify: Check for generated custom Algorithms, Actions, Tasks, and Pipelines files
      when: deployment_config.upgrade|bool
      changed_when: true
      delegate_to: "{{ master_host }}"
      run_once: true


